<?php

namespace App\Http\Controllers;

use App\Models\EmailDraft;
use App\Models\Meeting;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;

class EmailDraftController extends Controller
{
    // GET /api/email-drafts
    public function index(Request $request): JsonResponse
    {
        $drafts = EmailDraft::with(['meeting', 'author'])
            ->where('created_by', $request->user()->id)
            ->latest()
            ->paginate($request->integer('per_page', 20));

        return response()->json($drafts);
    }

    // POST /api/email-drafts
    public function store(Request $request): JsonResponse
    {
        $data = $request->validate([
            'meeting_id'           => ['required', 'exists:meetings,id'],
            'subject'              => ['required', 'string', 'max:500'],
            'body'                 => ['required', 'string'],
            'recipients'           => ['nullable', 'array'],
            'recipients.*'         => ['integer', 'exists:users,id'],
            'include_recording'    => ['sometimes', 'boolean'],
            'request_read_receipt' => ['sometimes', 'boolean'],
            'scheduled_at'         => ['nullable', 'date', 'after:now'],
        ]);

        $draft = EmailDraft::create(array_merge($data, [
            'created_by' => $request->user()->id,
            'status'     => 'draft',
        ]));

        return response()->json([
            'message' => 'Email draft created.',
            'draft'   => $draft->load(['meeting', 'author']),
        ], 201);
    }

    // GET /api/email-drafts/{draft}
    public function show(Request $request, EmailDraft $emailDraft): JsonResponse
    {
        $this->authorizeDraft($request, $emailDraft);

        return response()->json([
            'draft' => $emailDraft->load(['meeting.attendees', 'author']),
        ]);
    }

    // PATCH /api/email-drafts/{draft}
    public function update(Request $request, EmailDraft $emailDraft): JsonResponse
    {
        $this->authorizeDraft($request, $emailDraft);

        $data = $request->validate([
            'subject'              => ['sometimes', 'string', 'max:500'],
            'body'                 => ['sometimes', 'string'],
            'recipients'           => ['nullable', 'array'],
            'recipients.*'         => ['integer', 'exists:users,id'],
            'include_recording'    => ['sometimes', 'boolean'],
            'request_read_receipt' => ['sometimes', 'boolean'],
            'scheduled_at'         => ['nullable', 'date', 'after:now'],
        ]);

        $emailDraft->update($data);

        return response()->json([
            'message' => 'Draft updated.',
            'draft'   => $emailDraft->fresh(['meeting', 'author']),
        ]);
    }

    // POST /api/email-drafts/{draft}/send
    public function send(Request $request, EmailDraft $emailDraft): JsonResponse
    {
        $this->authorizeDraft($request, $emailDraft);

        if ($emailDraft->status === 'sent') {
            return response()->json(['message' => 'Email has already been sent.'], 422);
        }

        // TODO: Dispatch actual email sending job
        // SendMeetingEmailJob::dispatch($emailDraft);

        $emailDraft->update([
            'status'  => 'sent',
            'sent_at' => now(),
        ]);

        return response()->json(['message' => 'Email sent successfully.', 'draft' => $emailDraft->fresh()]);
    }

    // POST /api/email-drafts/{draft}/regenerate — AI regenerate body
    public function regenerate(Request $request, EmailDraft $emailDraft): JsonResponse
    {
        $this->authorizeDraft($request, $emailDraft);

        // TODO: Call AI service to regenerate email body
        $newBody = $emailDraft->body . "\n\n[Regenerated by AI]";

        $emailDraft->update(['body' => $newBody]);

        return response()->json([
            'message' => 'Email regenerated.',
            'draft'   => $emailDraft->fresh(),
        ]);
    }

    // DELETE /api/email-drafts/{draft}
    public function destroy(Request $request, EmailDraft $emailDraft): JsonResponse
    {
        $this->authorizeDraft($request, $emailDraft);

        $emailDraft->delete();

        return response()->json(['message' => 'Draft deleted.']);
    }

    // ── Helpers ──────────────────────────────────────────────────────────────

    private function authorizeDraft(Request $request, EmailDraft $emailDraft): void
    {
        if ($emailDraft->created_by !== $request->user()->id) {
            abort(403, 'Access denied.');
        }
    }
}